---
- name: Enabled mods
  apache2_module: name={{ item }} state=present
  become: yes
  become_method: sudo
  with_items:
    - rewrite
    - ssl
    - proxy
    - proxy_http
    - actions
    - fastcgi
    - headers
    - proxy
    - proxy_fcgi
    - proxy_http
  notify:
    - restart apache2